version: '3.7'

x-multicast-container: &multicast
    image: hl2ss_multicast
    build:
      context: .
    environment:
      API_URL: streamer:8000

services:
  streamer:
    build: redis-streamer
    container_name: redis-streamer
    ports:
     - 8000:8000
    environment:
      REDIS_URL: redis://redis:6379
      DISABLE_MULTI_DEVICE_PREFIXING: "1"
    depends_on:
     - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis_streamer/redis/redis_6789.conf:/usr/local/etc/redis/redis.conf
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  pvadapter:
    <<: *multicast
    command: ["BBN_redis_adapters.py", "pv"]

  # glladapter:
  #   *multicast
  #   command: ["BBN_redis_adapters.py", "vlc". "0"]

  # glfadapter:
  #   *multicast
  #   command: ["BBN_redis_adapters.py", "vlc". "1"]

  # grfadapter:
  #   *multicast
  #   command: ["BBN_redis_adapters.py", "vlc". "2"]

  # grradapter:
  #   *multicast
  #   command: ["BBN_redis_adapters.py", "vlc". "3"]

  # depthadapter:
  #   *multicast
  #   command: ["BBN_redis_adapters.py", "depth"]

  # imuacceladapter:
  #   *multicast
  #   command: ["BBN_redis_adapters.py", "accel"]

  # gyroadapter:
  #     *multicast
  #     command: ["BBN_redis_adapters.py", "gyro"]

  # magadapter:
  #     *multicast
  #     command: ["BBN_redis_adapters.py", "mag"]
